/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Produto;

/**
 *
 * @author jesp
 */
public class TelaProdutoCadastro extends javax.swing.JDialog {

    ProdutoController controller = new ProdutoController();

    public TelaProdutoCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_COD_Produto_ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Descricao_Produto_ = new javax.swing.JTextField();
        jTextField_Preco_Produto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));
        getContentPane().add(jTextField_COD_Produto_, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 50, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Descrição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 134, 90, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Preço");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 193, 72, -1));

        jTextField_Descricao_Produto_.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField_Descricao_Produto_, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 131, 360, -1));

        jTextField_Preco_Produto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextField_Preco_Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 190, 87, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Produto");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 40));

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        TelaProduto tp = new TelaProduto();
        
        if (jTextField_COD_Produto_.getText().isEmpty()) {
            Produto p = criaObjetoProduto();
            if(p != null){
                controller.saveProduto(p);
                
            }
        } else {
            Produto p = criaObjetoProduto();
            if(p != null){
                controller.updateProduto(p); 
                
            }
        }
        tp.preencheJTable();
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private Produto criaObjetoProduto() {
        Produto p = null;
        if (!jTextField_Descricao_Produto_.getText().isEmpty() && !jTextField_Preco_Produto.getText().isEmpty()) {

            try {
                p = new Produto();
                p.setCod(Integer.parseInt(jTextField_COD_Produto_.getText()));
                p.setDescricao(jTextField_Descricao_Produto_.getText());
                p.setPreco(Double.parseDouble(jTextField_Preco_Produto.getText()));
                System.out.println(p.getCod());
                dispose();
                return p;
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Favor, preencha todos os campos.");
        }
        return null;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaProdutoCadastro dialog = new TelaProdutoCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JTextField getjTextField_COD_Produto_() {
        return jTextField_COD_Produto_;
    }

    public void setjTextField_COD_Produto_(JTextField jTextField_COD_Produto_) {
        this.jTextField_COD_Produto_ = jTextField_COD_Produto_;
    }

    public JTextField getjTextField_Descricao_Produto_() {
        return jTextField_Descricao_Produto_;
    }

    public void setjTextField_Descricao_Produto_(JTextField jTextField_Descricao_Produto_) {
        this.jTextField_Descricao_Produto_ = jTextField_Descricao_Produto_;
    }

    public JTextField getjTextField_Preco_Produto() {
        return jTextField_Preco_Produto;
    }

    public void setjTextField_Preco_Produto(JTextField jTextField_Preco_Produto) {
        this.jTextField_Preco_Produto = jTextField_Preco_Produto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_COD_Produto_;
    private javax.swing.JTextField jTextField_Descricao_Produto_;
    private javax.swing.JTextField jTextField_Preco_Produto;
    // End of variables declaration//GEN-END:variables
}
