/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author L
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_COD_Cliente_ = new javax.swing.JTextField();
        jButton_Pesquisa_Cliente_ = new javax.swing.JButton();
        jButton_Novo_Cliente_ = new javax.swing.JButton();
        jButton_Editar_Cliente_ = new javax.swing.JButton();
        jButton_Excluir_Cliente_ = new javax.swing.JButton();
        jButton_Listar_Cliente_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Cliente_ = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_VoltarMenu_ = new javax.swing.JMenuItem();
        jMenuItem_Fazer_Logoff_ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CPF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 80, 30);

        jTextField_COD_Cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_COD_Cliente_ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_COD_Cliente_);
        jTextField_COD_Cliente_.setBounds(70, 110, 140, 30);

        jButton_Pesquisa_Cliente_.setText("Pesquisar");
        getContentPane().add(jButton_Pesquisa_Cliente_);
        jButton_Pesquisa_Cliente_.setBounds(230, 110, 100, 30);

        jButton_Novo_Cliente_.setText("Novo");
        jButton_Novo_Cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Novo_Cliente_ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Novo_Cliente_);
        jButton_Novo_Cliente_.setBounds(710, 670, 90, 30);

        jButton_Editar_Cliente_.setText("Editar");
        getContentPane().add(jButton_Editar_Cliente_);
        jButton_Editar_Cliente_.setBounds(820, 670, 90, 30);

        jButton_Excluir_Cliente_.setText("Excluir");
        getContentPane().add(jButton_Excluir_Cliente_);
        jButton_Excluir_Cliente_.setBounds(930, 670, 90, 30);

        jButton_Listar_Cliente_.setText("Listar");
        getContentPane().add(jButton_Listar_Cliente_);
        jButton_Listar_Cliente_.setBounds(20, 240, 90, 30);

        jTable_Cliente_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Sexo", "Data de Nascimento", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(jTable_Cliente_);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 1000, 350);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Cliente");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 0, 90, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clientes.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(670, 20, 350, 250);

        jMenu2.setText("Sair");

        jMenuItem_VoltarMenu_.setText("Voltar para o menu principal");
        jMenuItem_VoltarMenu_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_VoltarMenu_ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_VoltarMenu_);

        jMenuItem_Fazer_Logoff_.setText("Fazer Logoff");
        jMenuItem_Fazer_Logoff_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Fazer_Logoff_ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Fazer_Logoff_);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1154, 814));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_COD_Cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_COD_Cliente_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_COD_Cliente_ActionPerformed

    private void jMenuItem_VoltarMenu_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_VoltarMenu_ActionPerformed
        TelaMenu tela = new TelaMenu();
        tela.setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_VoltarMenu_ActionPerformed

    private void jMenuItem_Fazer_Logoff_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Fazer_Logoff_ActionPerformed
        TelaLog tela = new TelaLog();
        tela.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Fazer_Logoff_ActionPerformed

    private void jButton_Novo_Cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Novo_Cliente_ActionPerformed
      TelaClienteCadastro dialog = new TelaClienteCadastro(new JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton_Novo_Cliente_ActionPerformed

    
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Editar_Cliente_;
    private javax.swing.JButton jButton_Excluir_Cliente_;
    private javax.swing.JButton jButton_Listar_Cliente_;
    private javax.swing.JButton jButton_Novo_Cliente_;
    private javax.swing.JButton jButton_Pesquisa_Cliente_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Fazer_Logoff_;
    private javax.swing.JMenuItem jMenuItem_VoltarMenu_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Cliente_;
    private javax.swing.JTextField jTextField_COD_Cliente_;
    // End of variables declaration//GEN-END:variables
}
